import { generateId } from "./hrRepositoryUtils.js";

const permissionSeed = [
  { module: "hr", actions: ["view", "create", "edit", "approve"] },
  { module: "payroll", actions: ["view", "process", "approve"] },
  { module: "attendance", actions: ["view", "create", "approve"] },
  { module: "recruitment", actions: ["view", "create", "edit", "approve"] },
  { module: "performance", actions: ["view", "create", "edit", "approve"] },
  { module: "workflow", actions: ["view", "create", "edit", "approve"] },
  { module: "notifications", actions: ["view", "create", "edit"] },
  { module: "ai", actions: ["view"] },
];

const now = new Date().toISOString();

const seedStore = () => ({
  roles: [
    { id: "role-admin", name: "admin" },
    { id: "role-manager", name: "manager" },
    { id: "role-hr", name: "hr" },
    { id: "role-finance", name: "finance" },
    { id: "role-employee", name: "employee" },
  ],
  permissions: permissionSeed.flatMap(({ module, actions }) =>
    actions.map((action) => ({
      id: `${module}-${action}`,
      module,
      action,
    })),
  ),
  role_permissions: [
    { id: "rp-1", role_id: "role-admin", permission_id: "hr-view" },
    { id: "rp-2", role_id: "role-admin", permission_id: "payroll-process" },
    { id: "rp-3", role_id: "role-manager", permission_id: "hr-approve" },
    { id: "rp-4", role_id: "role-hr", permission_id: "recruitment-edit" },
    { id: "rp-5", role_id: "role-finance", permission_id: "payroll-approve" },
  ],
  employees: [
    {
      id: "emp-1001",
      user_id: "USR-ADMIN-1",
      organization_id: "ORG-INTERNAL",
      employee_code: "VM-001",
      name: "Aarav Admin",
      email: "admin@visamatrix.local",
      status: "active",
      department: "Executive",
      department_id: "dep-exec",
      job_title: "Chief Operations Officer",
      employment_type: "full_time",
      location: "Bengaluru",
      manager_id: null,
      attrition_risk: "low",
      joining_date: "2022-01-10",
      created_at: now,
      updated_at: now,
    },
    {
      id: "emp-1002",
      user_id: "USR-MANAGER-1",
      organization_id: "ORG-INTERNAL",
      employee_code: "VM-002",
      name: "Meera Manager",
      email: "manager@visamatrix.local",
      status: "active",
      department: "Human Resources",
      department_id: "dep-hr",
      job_title: "HR Manager",
      employment_type: "full_time",
      location: "Hyderabad",
      manager_id: "emp-1001",
      attrition_risk: "medium",
      joining_date: "2022-06-14",
      created_at: now,
      updated_at: now,
    },
    {
      id: "emp-1003",
      user_id: "USR-AGENT-1",
      organization_id: "ORG-INTERNAL",
      employee_code: "VM-003",
      name: "Rohan Agent",
      email: "agent@visamatrix.local",
      status: "active",
      department: "Operations",
      department_id: "dep-ops",
      job_title: "Visa Processing Executive",
      employment_type: "full_time",
      location: "Pune",
      manager_id: "emp-1002",
      attrition_risk: "high",
      joining_date: "2023-03-01",
      created_at: now,
      updated_at: now,
    },
  ],
  employee_salary_structure: [
    {
      id: "salary-emp-1002",
      employee_id: "emp-1002",
      currency: "INR",
      tax_regime: "new",
      salary_components: {
        basic: 85000,
        hra: 34000,
        special_allowance: 18000,
        retention_bonus: 5000,
        deductions: { pf: 1800, insurance: 900 },
      },
      effective_from: "2026-01-01",
      updated_at: now,
    },
    {
      id: "salary-emp-1003",
      employee_id: "emp-1003",
      currency: "INR",
      tax_regime: "old",
      salary_components: {
        basic: 42000,
        hra: 16800,
        special_allowance: 7000,
        shift_allowance: 3000,
        deductions: { pf: 1800, insurance: 700 },
      },
      effective_from: "2026-01-01",
      updated_at: now,
    },
  ],
  payroll_logs: [
    {
      id: "pay-2026-02-emp-1002",
      employee_id: "emp-1002",
      pay_period: "2026-02",
      gross_pay: 142000,
      tax_amount: 18700,
      net_pay: 121500,
      status: "processed",
      processed_at: "2026-03-01T09:00:00.000Z",
      payslip: {
        earnings: [
          { label: "Basic", value: 85000 },
          { label: "HRA", value: 34000 },
          { label: "Special Allowance", value: 18000 },
          { label: "Retention Bonus", value: 5000 },
        ],
        deductions: [
          { label: "PF", value: 1800 },
          { label: "Insurance", value: 900 },
          { label: "Tax", value: 18700 },
        ],
      },
    },
  ],
  workflow_definitions: [
    {
      id: "wf-leave-default",
      module: "attendance",
      name: "Leave Approval Workflow",
      steps: [
        { key: "employee", name: "Employee Submission", approverRole: "employee", order: 1 },
        { key: "manager", name: "Manager Approval", approverRole: "manager", order: 2 },
        { key: "hr", name: "HR Approval", approverRole: "hr", order: 3 },
      ],
      is_active: true,
      created_at: now,
    },
    {
      id: "wf-recruitment-default",
      module: "recruitment",
      name: "Candidate Hiring Workflow",
      steps: [
        { key: "screening", name: "Screening", approverRole: "hr", order: 1 },
        { key: "interview", name: "Panel Interview", approverRole: "manager", order: 2 },
        { key: "offer", name: "Offer Approval", approverRole: "hr", order: 3 },
      ],
      is_active: true,
      created_at: now,
    },
  ],
  workflow_instances: [
    {
      id: "wfi-1001",
      workflow_definition_id: "wf-leave-default",
      module: "attendance",
      reference_id: "leave-1001",
      status: "pending",
      current_step: 2,
      steps: [
        { key: "employee", status: "completed", acted_by: "emp-1003" },
        { key: "manager", status: "pending", acted_by: null },
        { key: "hr", status: "locked", acted_by: null },
      ],
      created_at: now,
      updated_at: now,
    },
  ],
  notifications: [
    {
      id: "hrn-1001",
      user_id: "USR-MANAGER-1",
      type: "workflow",
      message: "New leave request is waiting for manager approval.",
      read_status: false,
      reference_id: "leave-1001",
      created_at: now,
    },
  ],
  attendance_records: [
    {
      id: "att-1001",
      employee_id: "emp-1002",
      date: "2026-03-24",
      status: "present",
      check_in: "2026-03-24T09:06:00.000Z",
      check_out: "2026-03-24T18:15:00.000Z",
      hours_worked: 9.15,
      created_at: now,
      updated_at: now,
    },
  ],
  leave_requests: [
    {
      id: "leave-1001",
      employee_id: "emp-1003",
      type: "earned_leave",
      start_date: "2026-03-29",
      end_date: "2026-03-30",
      days: 2,
      reason: "Family travel",
      status: "pending",
      created_at: now,
      updated_at: now,
    },
  ],
  candidates: [
    {
      id: "cand-1001",
      name: "Ishita Rao",
      role: "Senior Recruiter",
      stage: "screening",
      source: "LinkedIn",
      owner: "Meera Manager",
      salary_expectation: 1400000,
      score: 82,
      created_at: now,
      updated_at: now,
    },
    {
      id: "cand-1002",
      name: "Karan Malhotra",
      role: "Payroll Specialist",
      stage: "interview",
      source: "Referral",
      owner: "Aarav Admin",
      salary_expectation: 1200000,
      score: 91,
      created_at: now,
      updated_at: now,
    },
  ],
  performance_reviews: [
    {
      id: "pr-1001",
      employee_id: "emp-1002",
      cycle: "2026-H1",
      rating: 4.8,
      goals_completed: 94,
      department: "Human Resources",
      feedback: "Built a reliable hiring and employee engagement rhythm.",
      status: "completed",
      created_at: now,
      updated_at: now,
    },
  ],
  audit_logs: [
    {
      id: generateId("audit"),
      action: "seeded",
      module: "hr",
      entity_id: "bootstrap",
      user_id: "USR-ADMIN-1",
      organization_id: "ORG-INTERNAL",
      metadata: { source: "hrStore" },
      timestamp: now,
    },
  ],
});

const hrStore = globalThis.__VM_HR_STORE__ ?? seedStore();
globalThis.__VM_HR_STORE__ = hrStore;

export const getHrStore = () => hrStore;

