import React from "react";
import { useEffect } from "react";
import { useState } from "react";
import FormEngine from "../components/FormEngine";
import StatCard from "../components/StatCard";
import { hrWorkspaceApi } from "../features/hr/api/hrWorkspaceApi";
import HrErrorState from "../features/hr/components/HrErrorState";
import HrLoadingState from "../features/hr/components/HrLoadingState";
import HrTrendBars from "../features/hr/components/HrTrendBars";
import HrWorkspaceLayout from "../features/hr/components/HrWorkspaceLayout";
import { useHrResource } from "../features/hr/hooks/useHrResource";
import { getFormSchema } from "../services/formService";

export default function HRDashboardWorkspace() {
  const [country, setCountry] = useState("");
  const [visaType, setVisaType] = useState("tourist");

  const { data, error, loading, reload } = useHrResource(
    async () => {
      const [dashboard, aiInsights, notifications] = await Promise.all([
        hrWorkspaceApi.getDashboard(),
        hrWorkspaceApi.getAiInsights(),
        hrWorkspaceApi.getNotifications(),
      ]);

      return { dashboard, aiInsights, notifications };
    },
    [],
  );

  useEffect(() => {
    async function testFormFetch() {
      const data = await getFormSchema("Japan", "tourist");
      console.log("FORM DATA:", data);
    }

    testFormFetch();
  }, []);

  if (loading) {
    return (
      <HrWorkspaceLayout title="HR Dashboard" description="Analytics-led workforce command center.">
        <HrLoadingState />
      </HrWorkspaceLayout>
    );
  }

  if (error) {
    return (
      <HrWorkspaceLayout title="HR Dashboard" description="Analytics-led workforce command center.">
        <HrErrorState message={error} onRetry={reload} />
      </HrWorkspaceLayout>
    );
  }

  const funnelItems = Object.entries(data.dashboard.analytics.hiringFunnel).map(([stage, value]) => ({
    stage,
    value,
  }));

  return (
    <HrWorkspaceLayout title="HR Dashboard" description="Analytics-led workforce command center.">
      <section className="panel">
        <select value={country} onChange={(e) => setCountry(e.target.value)}>
          <option value="">Select Country</option>
          <option value="Japan">Japan</option>
        </select>

        <FormEngine country={country} visaType={visaType} />
      </section>

      <section className="stats-grid">
        <StatCard title="Employees" value={data.dashboard.metrics.totalEmployees} icon="HC" color="#0f766e" />
        <StatCard title="Active Headcount" value={data.dashboard.metrics.activeEmployees} icon="AH" color="#1d4ed8" />
        <StatCard title="Open Positions" value={data.dashboard.metrics.openPositions} icon="OP" color="#b45309" />
        <StatCard title="Payroll Cost" value={`INR ${data.dashboard.metrics.payrollCost.toLocaleString()}`} icon="PC" color="#047857" />
        <StatCard title="Attrition Rate" value={`${data.dashboard.metrics.attritionRate}%`} icon="AR" color="#be123c" />
        <StatCard title="Approvals Pending" value={data.dashboard.highlights.approvalsPending} icon="WF" color="#4338ca" />
      </section>

      <section className="page-grid page-grid--two">
        <HrTrendBars title="Hiring Funnel" items={funnelItems} valueKey="value" labelKey="stage" />
        <HrTrendBars
          title="Department Performance"
          items={data.dashboard.analytics.departmentPerformance}
          valueKey="score"
          labelKey="department"
          formatter={(value) => `${value}/5`}
        />
      </section>

      <section className="page-grid page-grid--two">
        <article className="panel">
          <div className="panel__header">
            <div>
              <h3>AI Attrition Signals</h3>
              <p>Rule-based early warning signals with ML hook placeholders.</p>
            </div>
          </div>
          <div className="alert-stack">
            {data.aiInsights.attritionSignals.map((signal) => (
              <article className={`alert-card ${signal.risk_score >= 70 ? "alert-card--danger" : "alert-card--warning"}`} key={signal.employee_id}>
                <span className="alert-card__eyebrow">{signal.employee_name}</span>
                <strong>{signal.recommendation}</strong>
              </article>
            ))}
          </div>
        </article>

        <article className="panel">
          <div className="panel__header">
            <div>
              <h3>Operational Notifications</h3>
              <p>Workflow, payroll, and workforce alerts generated by the HR event bus.</p>
            </div>
          </div>
          <div className="alert-stack">
            {data.notifications.items.map((notification) => (
              <article className="alert-card alert-card--info" key={notification.id}>
                <span className="alert-card__eyebrow">{notification.type}</span>
                <strong>{notification.message}</strong>
              </article>
            ))}
          </div>
        </article>
      </section>
    </HrWorkspaceLayout>
  );
}
